-- Tabelas usadas pelo código (src/pages/*.jsx, src/components/Footer.jsx) que
-- NÃO estavam em schema_completo.sql — precisam existir no projeto Supabase
-- novo, senão o painel admin e partes do site (Sobre, Rodapé, Home) falham
-- silenciosamente ao buscar dados.
--
-- Rode este arquivo LOGO APÓS o schema_completo.sql.

-- ============================================================
-- 1) CATEGORIAS (usadas no painel admin e na listagem de cursos)
-- ============================================================
create table if not exists public.categorias (
  id bigint generated by default as identity primary key,
  nome text not null,
  created_at timestamptz not null default now()
);
alter table public.categorias enable row level security;
drop policy if exists "categorias: leitura publica" on public.categorias;
create policy "categorias: leitura publica" on public.categorias for select to anon, authenticated using (true);
drop policy if exists "categorias: insert autenticado" on public.categorias;
create policy "categorias: insert autenticado" on public.categorias for insert to authenticated with check (true);
drop policy if exists "categorias: update autenticado" on public.categorias;
create policy "categorias: update autenticado" on public.categorias for update to authenticated using (true) with check (true);
drop policy if exists "categorias: delete autenticado" on public.categorias;
create policy "categorias: delete autenticado" on public.categorias for delete to authenticated using (true);

-- categoria_id em cursos_cadastrados (o painel admin filtra/edita por este campo,
-- além do campo texto "categoria" já existente).
alter table public.cursos_cadastrados
  add column if not exists categoria_id bigint references public.categorias(id);

-- ============================================================
-- 2) GALERIA DA PÁGINA "SOBRE" (9 fotos, linha única id=1)
-- ============================================================
create table if not exists public.sobre_galeria (
  id bigint primary key,
  imagem_1 text, imagem_2 text, imagem_3 text,
  imagem_4 text, imagem_5 text, imagem_6 text,
  imagem_7 text, imagem_8 text, imagem_9 text,
  created_at timestamptz not null default now()
);
alter table public.sobre_galeria enable row level security;
drop policy if exists "sobre_galeria: leitura publica" on public.sobre_galeria;
create policy "sobre_galeria: leitura publica" on public.sobre_galeria for select to anon, authenticated using (true);
drop policy if exists "sobre_galeria: upsert autenticado" on public.sobre_galeria;
create policy "sobre_galeria: upsert autenticado" on public.sobre_galeria for insert to authenticated with check (true);
drop policy if exists "sobre_galeria: update autenticado" on public.sobre_galeria;
create policy "sobre_galeria: update autenticado" on public.sobre_galeria for update to authenticated using (true) with check (true);

-- ============================================================
-- 3) REDES SOCIAIS DA PÁGINA "SOBRE" (linha única id=1)
-- ============================================================
create table if not exists public.sobre_redes_sociais (
  id bigint primary key,
  facebook_imagem text, facebook_link text,
  instagram_imagem text, instagram_link text,
  youtube_imagem text, youtube_link text,
  reclameaqui_imagem text, reclameaqui_link text,
  google_imagem text, google_link text,
  created_at timestamptz not null default now()
);
alter table public.sobre_redes_sociais enable row level security;
drop policy if exists "sobre_redes_sociais: leitura publica" on public.sobre_redes_sociais;
create policy "sobre_redes_sociais: leitura publica" on public.sobre_redes_sociais for select to anon, authenticated using (true);
drop policy if exists "sobre_redes_sociais: insert autenticado" on public.sobre_redes_sociais;
create policy "sobre_redes_sociais: insert autenticado" on public.sobre_redes_sociais for insert to authenticated with check (true);
drop policy if exists "sobre_redes_sociais: update autenticado" on public.sobre_redes_sociais;
create policy "sobre_redes_sociais: update autenticado" on public.sobre_redes_sociais for update to authenticated using (true) with check (true);

-- ============================================================
-- 4) DESTAQUES DA PÁGINA "SOBRE" (imagem central + 8 tópicos, linha única id=1)
-- ============================================================
create table if not exists public.sobre_produto_destaque (
  id bigint primary key,
  imagem_url text,
  esquerda_1 text, esquerda_2 text, esquerda_3 text, esquerda_4 text,
  direita_1 text, direita_2 text, direita_3 text, direita_4 text,
  created_at timestamptz not null default now()
);
alter table public.sobre_produto_destaque enable row level security;
drop policy if exists "sobre_produto_destaque: leitura publica" on public.sobre_produto_destaque;
create policy "sobre_produto_destaque: leitura publica" on public.sobre_produto_destaque for select to anon, authenticated using (true);
drop policy if exists "sobre_produto_destaque: insert autenticado" on public.sobre_produto_destaque;
create policy "sobre_produto_destaque: insert autenticado" on public.sobre_produto_destaque for insert to authenticated with check (true);
drop policy if exists "sobre_produto_destaque: update autenticado" on public.sobre_produto_destaque;
create policy "sobre_produto_destaque: update autenticado" on public.sobre_produto_destaque for update to authenticated using (true) with check (true);

-- ============================================================
-- 5) CONTATO E REDES SOCIAIS DO RODAPÉ (linha única id=1)
-- ============================================================
create table if not exists public.contato_footer (
  id bigint primary key,
  endereco_linha1 text,
  endereco_linha2 text,
  telefone text,
  whatsapp_numero text,
  email text,
  instagram_url text,
  facebook_url text,
  linkedin_url text,
  created_at timestamptz not null default now()
);
alter table public.contato_footer enable row level security;
drop policy if exists "contato_footer: leitura publica" on public.contato_footer;
create policy "contato_footer: leitura publica" on public.contato_footer for select to anon, authenticated using (true);
drop policy if exists "contato_footer: insert autenticado" on public.contato_footer;
create policy "contato_footer: insert autenticado" on public.contato_footer for insert to authenticated with check (true);
drop policy if exists "contato_footer: update autenticado" on public.contato_footer;
create policy "contato_footer: update autenticado" on public.contato_footer for update to authenticated using (true) with check (true);

-- ============================================================
-- 6) CARROSSEL 3D DA HOME (até 12 fotos, linha única id=1)
-- ============================================================
create table if not exists public.home_carrossel_3d (
  id bigint primary key,
  imagem_1 text, imagem_2 text, imagem_3 text, imagem_4 text,
  imagem_5 text, imagem_6 text, imagem_7 text, imagem_8 text,
  imagem_9 text, imagem_10 text, imagem_11 text, imagem_12 text,
  created_at timestamptz not null default now()
);
alter table public.home_carrossel_3d enable row level security;
drop policy if exists "home_carrossel_3d: leitura publica" on public.home_carrossel_3d;
create policy "home_carrossel_3d: leitura publica" on public.home_carrossel_3d for select to anon, authenticated using (true);
drop policy if exists "home_carrossel_3d: insert autenticado" on public.home_carrossel_3d;
create policy "home_carrossel_3d: insert autenticado" on public.home_carrossel_3d for insert to authenticated with check (true);
drop policy if exists "home_carrossel_3d: update autenticado" on public.home_carrossel_3d;
create policy "home_carrossel_3d: update autenticado" on public.home_carrossel_3d for update to authenticated using (true) with check (true);
